### PR TITLE
Nested merge keys

### PR DESCRIPTION
**Pull request by mathroc**
I think there is a bug with nested keys in some case. For starters I updated the merge key test to show the behavior I expect and the error that is instead produce

### CODE REVIEW

**Comment by mathroc** [comment]
I didn't realise that tests weren't run on travis on this repo. Is this the right place to make PR ?

here is the phpunit output:


```
PHPUnit 4.2.6 by Sebastian Bergmann.

Configuration read from /home/mathieu/Project/yaml/phpunit.xml.dist

...............................................................  63 / 358 ( 17%)
............................................................... 126 / 358 ( 35%)
............................................................... 189 / 358 ( 52%)
...................................................[31;1mE[0m........... 252 / 358 ( 70%)
............................................................... 315 / 358 ( 87%)
...........................................

Time: 262 ms, Memory: 6.50Mb

There was 1 error:

1) Symfony\Component\Yaml\Tests\ParserTest::testSpecifications with data set #52 ('sfMergeKey', 'array (
  \'foo\' => 
  array (
    \'a\' => \'Steve\',
    \'b\' => \'Clark\',
    \'c\' => \'Brian\',
  ),
  \'taz\' => 
  array (
    \'a\' => \'Steve\',
    \'b\' => \'Clark\',
    \'w\' => 
    array (
      \'p\' => 1234,
    ),
  ),
  \'bar\' => 
  array (
    \'a\' => \'before\',
    \'d\' => \'other\',
    \'b\' => \'new\',
    \'c\' => 
    array (
      \'foo\' => \'bar\',
      \'bar\' => \'foo\',
    ),
    \'x\' => \'Oren\',
  ),
  \'duplicate\' => 
  array (
    \'foo\' => \'bar\',
  ),
  \'foo2\' => 
  array (
    \'a\' => \'Ballmer\',
  ),
  \'ding\' => 
  array (
    0 => \'fi\',
    1 => \'fei\',
    2 => \'fo\',
    3 => \'fam\',
  ),
  \'check\' => 
  array (
    \'a\' => \'Steve\',
    \'b\' => \'Clark\',
    \'c\' => \'Brian\',
    0 => \'fi\',
    1 => \'fei\',
    2 => \'fo\',
    3 => \'fam\',
    \'isit\' => \'tested\',
  ),
  \'head\' => 
  array (
    \'a\' => \'Steve\',
    \'b\' => \'Clark\',
    \'c\' => \'Brian\',
    0 => \'fi\',
    1 => \'fei\',
    2 => \'fo\',
    3 => \'fam\',
  ),
  \'nested\' => 
  array (
    \'a\' => \'Steve\',
    \'d\' => \'Doug\',
    \'w\' => 
    array (
      \'h\' => \'Henry\',
    ),
    \'z\' => 
    array (
      \'h\' => \'Henry\',
    ),
  ),
)', 'foo: &foo
    a: Steve
    b: Clark
    c: Brian
taz: &taz
    a: Steve
    w:
        p: 1234
bar:
    a: before
    d: other
    <<: *foo
    b: new
    x: Oren
    c:
        foo: bar
        foo: ignore
        bar: foo
duplicate:
    foo: bar
    foo: ignore
foo2: &foo2
    a: Ballmer
ding: &dong [ fi, fei, fo, fam]
check:
    <<:
        - *foo
        - *dong
    isit: tested
head:
    <<: [ *foo , *dong , *foo2 ]
nested:
    <<: *taz
    d: Doug
    w: &nestedref
        h: Henry
    z:
        <<: *nestedref
', 'Simple In Place Substitution')
Symfony\Component\Yaml\Exception\ParseException: YAML merge keys used with a scalar value instead of an array at line 38 (near "<<: *nestedref").
[37;41m                                       [0m
[37;41mFAILURES!                              [0m
[37;41mTests: 358, Assertions: 536, Errors: 1.[0m
```

**Comment by GrahamCampbell** [comment]
Wrong repo. All PRs must go to symfony.

**Comment by mathroc** [comment]
thx @GrahamCampbell , I'll do that (I just found https://github.com/symfony/symfony/blob/2.8/CONTRIBUTING.md )

**Comment by mathroc** [comment]
symfony/symfony#15241

**Pull request closed without merging**
